app:
    datasource:
      jdbc-url: jdbc:postgresql://${DBHOST:amazonaws.com}:${PORT:5432}/${DBNAME:dfnmcig94bc3ks}?currentSchema=findcomp_user,public
      username: ${DB_USER:bvvmwhjtdzvpjf}
      password: ${DB_PASS:365591}
      pool-size: 30

application:
  jwt:
    secretKey: ${JWT_SECRET:123}
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 3
