app:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/findcomp?currentSchema=findcomp_user,public
      username: findcomp_user
      password: findcomp_user
      pool-size: 30

application:
  jwt:
    secretKey: 123456789012345678901234567890123456789012345678901234567890asdadadadqwqeqwe!##
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 3